insert into orders (id, description, status) values (1, 'Beef - Diced', 0);
insert into orders (id, description, status) values (2, 'Wine - White, Pinot Grigio', 2);
insert into orders (id, description, status) values (3, 'Snapple Lemon Tea', 0);
insert into orders (id, description, status) values (4, 'Rice - 7 Grain Blend', 2);
insert into orders (id, description, status) values (5, 'Split Peas - Yellow, Dry', 1);
insert into orders (id, description, status) values (6, 'Dragon Fruit', 2);
insert into orders (id, description, status) values (7, 'Trout - Hot Smkd, Dbl Fillet', 1);
insert into orders (id, description, status) values (8, 'Fish - Base, Bouillion', 2);
insert into orders (id, description, status) values (9, 'Muffin Mix - Carrot', 0);
insert into orders (id, description, status) values (10, 'Lychee - Canned', 0);
insert into orders (id, description, status) values (11, 'Blouse / Shirt / Sweater', 2);
insert into orders (id, description, status) values (12, 'Compound - Raspberry', 1);
insert into orders (id, description, status) values (13, 'Beef - Top Sirloin', 1);
insert into orders (id, description, status) values (14, 'Wine - Magnotta - Pinot Gris Sr', 0);
insert into orders (id, description, status) values (15, 'Sauce - White, Mix', 1);
insert into orders (id, description, status) values (16, 'Trueblue - Blueberry 12x473ml', 1);
insert into orders (id, description, status) values (17, 'Cake - French Pear Tart', 2);
insert into orders (id, description, status) values (18, 'Yoplait Drink', 2);
insert into orders (id, description, status) values (19, 'Sugar - Individual Portions', 2);
insert into orders (id, description, status) values (20, 'Wine - Black Tower Qr', 0);
insert into orders (id, description, status) values (21, 'Eggplant - Regular', 2);
insert into orders (id, description, status) values (22, 'Rosemary - Fresh', 2);
insert into orders (id, description, status) values (23, 'Juice - Pineapple, 48 Oz', 2);
insert into orders (id, description, status) values (24, 'Ham - Proscuitto', 2);
insert into orders (id, description, status) values (25, 'Cream - 18%', 2);
insert into orders (id, description, status) values (26, 'Beef - Kindney, Whole', 1);
insert into orders (id, description, status) values (27, 'Sauce Bbq Smokey', 0);
insert into orders (id, description, status) values (28, 'Mint - Fresh', 2);
insert into orders (id, description, status) values (29, 'Salami - Genova', 1);
insert into orders (id, description, status) values (30, 'Myers Planters Punch', 1);
insert into orders (id, description, status) values (31, 'Table Cloth 90x90 White', 2);
insert into orders (id, description, status) values (32, 'Pastry - Lemon Danish - Mini', 0);
insert into orders (id, description, status) values (33, 'Muffin - Mix - Creme Brule 15l', 1);
insert into orders (id, description, status) values (34, 'Pepper - Chili Powder', 2);
insert into orders (id, description, status) values (35, 'Sole - Iqf', 1);
insert into orders (id, description, status) values (36, 'Fiddlehead - Frozen', 2);
insert into orders (id, description, status) values (37, 'Butter - Pod', 2);
insert into orders (id, description, status) values (38, 'Dried Cranberries', 2);
insert into orders (id, description, status) values (39, 'Cookie Dough - Chocolate Chip', 1);
insert into orders (id, description, status) values (40, 'Daves Island Stinger', 1);
insert into orders (id, description, status) values (41, 'Wine - Rosso Del Veronese Igt', 0);
insert into orders (id, description, status) values (42, 'Longos - Chicken Cordon Bleu', 2);
insert into orders (id, description, status) values (43, 'Beef - Rouladin, Sliced', 0);
insert into orders (id, description, status) values (44, 'Tart - Raisin And Pecan', 1);
insert into orders (id, description, status) values (45, 'Flower - Commercial Bronze', 2);
insert into orders (id, description, status) values (46, 'Rum - Coconut, Malibu', 0);
insert into orders (id, description, status) values (47, 'Praline Paste', 1);
insert into orders (id, description, status) values (48, 'Stainless Steel Cleaner Vision', 1);
insert into orders (id, description, status) values (49, 'Flour - Chickpea', 0);
insert into orders (id, description, status) values (50, 'Sugar - Crumb', 2);
insert into orders (id, description, status) values (51, 'Sauce - Salsa', 0);
insert into orders (id, description, status) values (52, 'Appetizer - Cheese Bites', 2);
insert into orders (id, description, status) values (53, 'Pepper - White, Whole', 2);
insert into orders (id, description, status) values (54, 'Bread - Calabrese Baguette', 0);
insert into orders (id, description, status) values (55, 'Cheese - Grie Des Champ', 2);
insert into orders (id, description, status) values (56, 'Tomato Paste', 0);
insert into orders (id, description, status) values (57, 'Tequila Rose Cream Liquor', 1);
insert into orders (id, description, status) values (58, 'Squash - Guords', 2);
insert into orders (id, description, status) values (59, 'Sword Pick Asst', 1);
insert into orders (id, description, status) values (60, 'Mushroom Morel Fresh', 0);
insert into orders (id, description, status) values (61, 'Durian Fruit', 2);
insert into orders (id, description, status) values (62, 'Tomatoes - Hot House', 2);
insert into orders (id, description, status) values (63, 'Cheese - Boursin, Garlic / Herbs', 1);
insert into orders (id, description, status) values (64, 'Table Cloth 90x90 White', 2);
insert into orders (id, description, status) values (65, 'Pastry - Plain Baked Croissant', 2);
insert into orders (id, description, status) values (66, 'Yogurt - Peach, 175 Gr', 1);
insert into orders (id, description, status) values (67, 'Syrup - Monin, Amaretta', 1);
insert into orders (id, description, status) values (68, 'Dried Apple', 1);
insert into orders (id, description, status) values (69, 'Wine - Casillero Deldiablo', 2);
insert into orders (id, description, status) values (70, 'Tea - Herbal I Love Lemon', 2);
insert into orders (id, description, status) values (71, 'Flour - Semolina', 1);
insert into orders (id, description, status) values (72, 'Horseradish - Prepared', 0);
insert into orders (id, description, status) values (73, 'Cake Circle, Paprus', 2);
insert into orders (id, description, status) values (74, 'Stock - Beef, White', 0);
insert into orders (id, description, status) values (75, 'Bread Base - Gold Formel', 0);
insert into orders (id, description, status) values (76, 'Beans - Butter Lrg Lima', 1);
insert into orders (id, description, status) values (77, 'Pork - Chop, Frenched', 2);
insert into orders (id, description, status) values (78, 'Toamtoes 6x7 Select', 2);
insert into orders (id, description, status) values (79, 'Lemon Balm - Fresh', 2);
insert into orders (id, description, status) values (80, 'Lettuce - Curly Endive', 2);
insert into orders (id, description, status) values (81, 'Wine - Wyndham Estate Bin 777', 0);
insert into orders (id, description, status) values (82, 'Cookies Oatmeal Raisin', 0);
insert into orders (id, description, status) values (83, 'Pasta - Penne, Rigate, Dry', 0);
insert into orders (id, description, status) values (84, 'Island Oasis - Pina Colada', 2);
insert into orders (id, description, status) values (85, 'Pears - Fiorelle', 2);
insert into orders (id, description, status) values (86, 'Cookie - Dough Variety', 0);
insert into orders (id, description, status) values (87, 'Foam Cup 6 Oz', 0);
insert into orders (id, description, status) values (88, 'Crab Meat Claw Pasteurise', 0);
insert into orders (id, description, status) values (89, 'Shrimp - Black Tiger 13/15', 0);
insert into orders (id, description, status) values (90, 'Wine - Barossa Valley Estate', 0);
insert into orders (id, description, status) values (91, 'Tomatoes Tear Drop', 0);
insert into orders (id, description, status) values (92, 'Ham - Cooked', 0);
insert into orders (id, description, status) values (93, 'Corn - Mini', 1);
insert into orders (id, description, status) values (94, 'Wine - Trimbach Pinot Blanc', 2);
insert into orders (id, description, status) values (95, 'Chilli Paste, Hot Sambal Oelek', 0);
insert into orders (id, description, status) values (96, 'Lid - 0090 Clear', 2);
insert into orders (id, description, status) values (97, 'Calaloo', 0);
insert into orders (id, description, status) values (98, 'Wine - Alicanca Vinho Verde', 1);
insert into orders (id, description, status) values (99, 'Island Oasis - Sweet And Sour Mix', 2);
insert into orders (id, description, status) values (100, 'Tart - Pecan Butter Squares', 2);
insert into orders (id, description, status) values (101, 'Wine - White, Riesling, Semi - Dry', 0);
insert into orders (id, description, status) values (102, 'Five Alive Citrus', 2);
insert into orders (id, description, status) values (103, 'Tomato - Plum With Basil', 1);
insert into orders (id, description, status) values (104, 'Compound - Rum', 0);
insert into orders (id, description, status) values (105, 'Soup - Knorr, Veg / Beef', 0);
insert into orders (id, description, status) values (106, 'Cups 10oz Trans', 2);
insert into orders (id, description, status) values (107, 'Cheese - Montery Jack', 2);
insert into orders (id, description, status) values (108, 'Bananas', 0);
insert into orders (id, description, status) values (109, 'Bread - Flat Bread', 1);
insert into orders (id, description, status) values (110, 'Crab - Claws, 26 - 30', 2);
insert into orders (id, description, status) values (111, 'Langers - Cranberry Cocktail', 0);
insert into orders (id, description, status) values (112, 'Lettuce - Arugula', 0);
insert into orders (id, description, status) values (113, 'Chicken - Livers', 1);
insert into orders (id, description, status) values (114, 'Capers - Pickled', 1);
insert into orders (id, description, status) values (115, 'Veal - Heart', 2);
insert into orders (id, description, status) values (116, 'Wine - Magnotta - Cab Sauv', 0);
insert into orders (id, description, status) values (117, 'Rabbit - Whole', 1);
insert into orders (id, description, status) values (118, 'The Pop Shoppe - Grape', 1);
insert into orders (id, description, status) values (119, 'Beef - Eye Of Round', 2);
insert into orders (id, description, status) values (120, 'Food Colouring - Orange', 2);
insert into orders (id, description, status) values (121, 'Rum - Coconut, Malibu', 1);
insert into orders (id, description, status) values (122, 'Mushroom - Chantrelle, Fresh', 0);
insert into orders (id, description, status) values (123, 'Cardamon Seed / Pod', 0);
insert into orders (id, description, status) values (124, 'Squid - Breaded', 0);
insert into orders (id, description, status) values (125, 'Sour Cream', 2);
insert into orders (id, description, status) values (126, 'Country Roll', 0);
insert into orders (id, description, status) values (127, 'Strawberries - California', 1);
insert into orders (id, description, status) values (128, 'Calvados - Boulard', 2);
insert into orders (id, description, status) values (129, 'Paste - Black Olive', 2);
insert into orders (id, description, status) values (130, 'Ocean Spray - Ruby Red', 2);
insert into orders (id, description, status) values (131, 'Hot Chocolate - Individual', 1);
insert into orders (id, description, status) values (132, 'Cape Capensis - Fillet', 2);
insert into orders (id, description, status) values (133, 'Creme De Cacao White', 0);
insert into orders (id, description, status) values (134, 'Cornstarch', 0);
insert into orders (id, description, status) values (135, 'Juice - Ocean Spray Kiwi', 0);
insert into orders (id, description, status) values (136, 'Wine - Red, Pelee Island Merlot', 0);
insert into orders (id, description, status) values (137, 'Pepper - Chili Powder', 0);
insert into orders (id, description, status) values (138, 'Versatainer Nc - 888', 2);
insert into orders (id, description, status) values (139, 'Prunes - Pitted', 0);
insert into orders (id, description, status) values (140, 'Pork - Sausage Casing', 0);
insert into orders (id, description, status) values (141, 'Soup - Campbells Asian Noodle', 1);
insert into orders (id, description, status) values (142, 'Wine - Savigny - Les - Beaune', 1);
insert into orders (id, description, status) values (143, 'Soup - Knorr, Country Bean', 2);
insert into orders (id, description, status) values (144, 'Wine - Champagne Brut Veuve', 2);
insert into orders (id, description, status) values (145, 'Bread - Pumpernickle, Rounds', 1);
insert into orders (id, description, status) values (146, 'Tart Shells - Sweet, 4', 0);
insert into orders (id, description, status) values (147, 'Calypso - Strawberry Lemonade', 2);
insert into orders (id, description, status) values (148, 'Muffin Batt - Ban Dream Zero', 2);
insert into orders (id, description, status) values (149, 'Cheese - Sheep Milk', 1);
insert into orders (id, description, status) values (150, 'Pasta - Ravioli', 1);
insert into orders (id, description, status) values (151, 'Pears - Bosc', 1);
insert into orders (id, description, status) values (152, 'Marzipan 50/50', 2);
insert into orders (id, description, status) values (153, 'Beer - True North Strong Ale', 2);
insert into orders (id, description, status) values (154, 'Lentils - Red, Dry', 2);
insert into orders (id, description, status) values (155, 'Hold Up Tool Storage Rack', 2);
insert into orders (id, description, status) values (156, 'Assorted Desserts', 1);
insert into orders (id, description, status) values (157, 'Clams - Littleneck, Whole', 0);
insert into orders (id, description, status) values (158, 'Squash - Guords', 0);
insert into orders (id, description, status) values (159, 'Icecream - Dibs', 2);
insert into orders (id, description, status) values (160, 'Wine - Sauvignon Blanc Oyster', 0);
insert into orders (id, description, status) values (161, 'Wine - Soave Folonari', 1);
insert into orders (id, description, status) values (162, 'Crab - Claws, 26 - 30', 0);
insert into orders (id, description, status) values (163, 'Soup - Campbells Pasta Fagioli', 0);
insert into orders (id, description, status) values (164, 'Wine - Red Oakridge Merlot', 1);
insert into orders (id, description, status) values (165, 'Cheese - Brie', 2);
insert into orders (id, description, status) values (166, 'Appetizer - Sausage Rolls', 2);
insert into orders (id, description, status) values (167, 'Noodles - Steamed Chow Mein', 2);
insert into orders (id, description, status) values (168, 'Plaintain', 1);
insert into orders (id, description, status) values (169, 'Yogurt - Raspberry, 175 Gr', 0);
insert into orders (id, description, status) values (170, 'Lettuce - Green Leaf', 0);
insert into orders (id, description, status) values (171, 'Fenngreek Seed', 2);
insert into orders (id, description, status) values (172, 'Muffin - Bran Ind Wrpd', 0);
insert into orders (id, description, status) values (173, 'Bread - Wheat Baguette', 0);
insert into orders (id, description, status) values (174, 'Soup - Knorr, Ministrone', 1);
insert into orders (id, description, status) values (175, 'Bread - Burger', 2);
insert into orders (id, description, status) values (176, 'Shrimp - Baby, Cold Water', 2);
insert into orders (id, description, status) values (177, 'Honey - Liquid', 1);
insert into orders (id, description, status) values (178, 'Bread - Frozen Basket Variety', 0);
insert into orders (id, description, status) values (179, 'Bread - Raisin', 1);
insert into orders (id, description, status) values (180, 'Cheese - Cheddar, Mild', 2);
insert into orders (id, description, status) values (181, 'Juice - Clamato, 341 Ml', 0);
insert into orders (id, description, status) values (182, 'Flavouring - Orange', 0);
insert into orders (id, description, status) values (183, 'Rice - Brown', 1);
insert into orders (id, description, status) values (184, 'Tequila - Sauza Silver', 1);
insert into orders (id, description, status) values (185, 'Tamarillo', 1);
insert into orders (id, description, status) values (186, 'Pickle - Dill', 2);
insert into orders (id, description, status) values (187, 'Water - Perrier', 2);
insert into orders (id, description, status) values (188, 'Oil - Safflower', 2);
insert into orders (id, description, status) values (189, 'Cornish Hen', 2);
insert into orders (id, description, status) values (190, 'Sauce - Rosee', 1);
insert into orders (id, description, status) values (191, 'Pepper - Chillies, Crushed', 2);
insert into orders (id, description, status) values (192, 'Guinea Fowl', 0);
insert into orders (id, description, status) values (193, 'Pastry - Cherry Danish - Mini', 1);
insert into orders (id, description, status) values (194, 'Juice - Ocean Spray Cranberry', 1);
insert into orders (id, description, status) values (195, 'Pasta - Cappellini, Dry', 2);
insert into orders (id, description, status) values (196, 'Bread - Onion Focaccia', 0);
insert into orders (id, description, status) values (197, 'Coffee Swiss Choc Almond', 0);
insert into orders (id, description, status) values (198, 'Mushroom - King Eryingii', 2);
insert into orders (id, description, status) values (199, 'Cleaner - Comet', 2);
insert into orders (id, description, status) values (200, 'Chinese Lemon Pork', 0);
insert into orders (id, description, status) values (201, 'Foam Tray S2', 2);
insert into orders (id, description, status) values (202, 'Marsala - Sperone, Fine, D.o.c.', 1);
insert into orders (id, description, status) values (203, 'Duck - Whole', 2);
insert into orders (id, description, status) values (204, 'Wine - Montecillo Rioja Crianza', 1);
insert into orders (id, description, status) values (205, 'Bag Clear 10 Lb', 1);
insert into orders (id, description, status) values (206, 'Basil - Seedlings Cookstown', 0);
insert into orders (id, description, status) values (207, 'Asparagus - Mexican', 1);
insert into orders (id, description, status) values (208, 'Cheese - Bakers Cream Cheese', 2);
insert into orders (id, description, status) values (209, 'Gingerale - Schweppes, 355 Ml', 1);
insert into orders (id, description, status) values (210, 'Dooleys Toffee', 2);
insert into orders (id, description, status) values (211, 'Sage - Fresh', 2);
insert into orders (id, description, status) values (212, 'Butter - Salted, Micro', 1);
insert into orders (id, description, status) values (213, 'Pepper - Paprika, Hungarian', 2);
insert into orders (id, description, status) values (214, 'Pickerel - Fillets', 1);
insert into orders (id, description, status) values (215, 'Soup - Knorr, Chicken Gumbo', 0);
insert into orders (id, description, status) values (216, 'Ham - Procutinni', 2);
insert into orders (id, description, status) values (217, 'Catfish - Fillets', 2);
insert into orders (id, description, status) values (218, 'Pecan Raisin - Tarts', 0);
insert into orders (id, description, status) values (219, 'Cake Sheet Combo Party Pack', 1);
insert into orders (id, description, status) values (220, 'Steel Wool', 1);
insert into orders (id, description, status) values (221, 'Carbonated Water - Blackberry', 0);
insert into orders (id, description, status) values (222, 'Limes', 2);
insert into orders (id, description, status) values (223, 'Lemon Tarts', 0);
insert into orders (id, description, status) values (224, 'Sauce - Gravy, Au Jus, Mix', 1);
insert into orders (id, description, status) values (225, 'Wine - Red, Gamay Noir', 2);
insert into orders (id, description, status) values (226, 'Coriander - Ground', 1);
insert into orders (id, description, status) values (227, 'Soup - Campbells', 2);
insert into orders (id, description, status) values (228, 'Fish - Base, Bouillion', 0);
insert into orders (id, description, status) values (229, 'Nantuket Peach Orange', 1);
insert into orders (id, description, status) values (230, 'Marsala - Sperone, Fine, D.o.c.', 2);
insert into orders (id, description, status) values (231, 'Sachet', 0);
insert into orders (id, description, status) values (232, 'Beef - Ground Medium', 1);
insert into orders (id, description, status) values (233, 'Nestea - Ice Tea, Diet', 1);
insert into orders (id, description, status) values (234, 'Appetizer - Chicken Satay', 0);
insert into orders (id, description, status) values (235, 'Soy Protein', 1);
insert into orders (id, description, status) values (236, 'Energy Drink Red Bull', 1);
insert into orders (id, description, status) values (237, 'Blue Curacao - Marie Brizard', 0);
insert into orders (id, description, status) values (238, 'Muffin - Mix - Bran And Maple 15l', 1);
insert into orders (id, description, status) values (239, 'Cloves - Ground', 0);
insert into orders (id, description, status) values (240, 'Beef - Shank', 1);
insert into orders (id, description, status) values (241, 'Cookies - Englishbay Chochip', 0);
insert into orders (id, description, status) values (242, 'Chocolate - Compound Coating', 2);
insert into orders (id, description, status) values (243, 'Cookie Trail Mix', 2);
insert into orders (id, description, status) values (244, 'Olives - Black, Pitted', 2);
insert into orders (id, description, status) values (245, 'Pastry - Carrot Muffin - Mini', 1);
insert into orders (id, description, status) values (246, 'Chicken Giblets', 1);
insert into orders (id, description, status) values (247, 'Flour - Pastry', 2);
insert into orders (id, description, status) values (248, 'Wiberg Cure', 2);
insert into orders (id, description, status) values (249, 'Beer - Alexander Kieths, Pale Ale', 1);
insert into orders (id, description, status) values (250, 'Beer - Camerons Auburn', 0);
insert into orders (id, description, status) values (251, 'Yoplait Drink', 0);
insert into orders (id, description, status) values (252, 'Cookie Dough - Chunky', 1);
insert into orders (id, description, status) values (253, 'Capon - Breast, Double, Wing On', 0);
insert into orders (id, description, status) values (254, 'Lychee', 0);
insert into orders (id, description, status) values (255, 'Spic And Span All Purpose', 0);
insert into orders (id, description, status) values (256, 'Chickensplit Half', 1);
insert into orders (id, description, status) values (257, 'Raspberries - Frozen', 0);
insert into orders (id, description, status) values (258, 'Lettuce - Lolla Rosa', 0);
insert into orders (id, description, status) values (259, 'Broom - Angled', 0);
insert into orders (id, description, status) values (260, 'Chevere Logs', 1);
insert into orders (id, description, status) values (261, 'Longos - Chicken Wings', 2);
insert into orders (id, description, status) values (262, 'Lid - 16 Oz And 32 Oz', 1);
insert into orders (id, description, status) values (263, 'Tilapia - Fillets', 1);
insert into orders (id, description, status) values (264, 'Tobasco Sauce', 0);
insert into orders (id, description, status) values (265, 'Mushroom - Portebello', 2);
insert into orders (id, description, status) values (266, 'Cookie Double Choco', 1);
insert into orders (id, description, status) values (267, 'Tahini Paste', 1);
insert into orders (id, description, status) values (268, 'Veal - Provimi Inside', 2);
insert into orders (id, description, status) values (269, 'Green Tea Refresher', 2);
insert into orders (id, description, status) values (270, 'Cake Circle, Foil, Scallop', 2);
insert into orders (id, description, status) values (271, 'Vol Au Vents', 1);
insert into orders (id, description, status) values (272, 'Cheese - Roquefort Pappillon', 2);
insert into orders (id, description, status) values (273, 'Bread Base - Italian', 2);
insert into orders (id, description, status) values (274, 'Butter - Pod', 1);
insert into orders (id, description, status) values (275, 'Calvados - Boulard', 1);
insert into orders (id, description, status) values (276, 'Wine - Barolo Fontanafredda', 2);
insert into orders (id, description, status) values (277, 'Spaghetti Squash', 0);
insert into orders (id, description, status) values (278, 'Truffle Shells - White Chocolate', 0);
insert into orders (id, description, status) values (279, 'Fiddlehead - Frozen', 0);
insert into orders (id, description, status) values (280, 'Mix - Cocktail Ice Cream', 0);
insert into orders (id, description, status) values (281, 'Lamb - Sausage Casings', 1);
insert into orders (id, description, status) values (282, 'Compound - Strawberry', 2);
insert into orders (id, description, status) values (283, 'Pasta - Lasagna Noodle, Frozen', 2);
insert into orders (id, description, status) values (284, 'Bouillion - Fish', 0);
insert into orders (id, description, status) values (285, 'Kiwi', 2);
insert into orders (id, description, status) values (286, 'Savory', 2);
insert into orders (id, description, status) values (287, 'Beer - Mcauslan Apricot', 2);
insert into orders (id, description, status) values (288, 'Lettuce - Lolla Rosa', 2);
insert into orders (id, description, status) values (289, 'Coffee Cup 12oz 5342cd', 2);
insert into orders (id, description, status) values (290, 'Orange Roughy 4/6 Oz', 1);
insert into orders (id, description, status) values (291, 'Brandy - Orange, Mc Guiness', 2);
insert into orders (id, description, status) values (292, 'Sauce - Bernaise, Mix', 2);
insert into orders (id, description, status) values (293, 'Madeira', 0);
insert into orders (id, description, status) values (294, 'Blackberries', 2);
insert into orders (id, description, status) values (295, 'Table Cloth 62x114 White', 2);
insert into orders (id, description, status) values (296, 'Sugar - Crumb', 2);
insert into orders (id, description, status) values (297, 'Bar Energy Chocchip', 1);
insert into orders (id, description, status) values (298, 'Coffee - Frthy Coffee Crisp', 1);
insert into orders (id, description, status) values (299, 'Bread - White, Unsliced', 0);
insert into orders (id, description, status) values (300, 'Wine - Red, Cooking', 0);
insert into orders (id, description, status) values (301, 'Chocolate Bar - Smarties', 0);
insert into orders (id, description, status) values (302, 'Cactus Pads', 0);
insert into orders (id, description, status) values (303, 'Bay Leaf', 2);
insert into orders (id, description, status) values (304, 'Tart - Pecan Butter Squares', 2);
insert into orders (id, description, status) values (305, 'Garbage Bags - Black', 2);
insert into orders (id, description, status) values (306, 'Cake - Night And Day Choclate', 2);
insert into orders (id, description, status) values (307, 'Cookies - Englishbay Wht', 2);
insert into orders (id, description, status) values (308, 'Trueblue - Blueberry', 2);
insert into orders (id, description, status) values (309, 'Fudge - Cream Fudge', 2);
insert into orders (id, description, status) values (310, 'Cup - 8oz Coffee Perforated', 2);
insert into orders (id, description, status) values (311, 'Cake Circle, Foil, Scallop', 2);
insert into orders (id, description, status) values (312, 'Squash - Pepper', 2);
insert into orders (id, description, status) values (313, 'Soup Campbells Turkey Veg.', 1);
insert into orders (id, description, status) values (314, 'Plastic Wrap', 2);
insert into orders (id, description, status) values (315, 'Veal - Heart', 2);
insert into orders (id, description, status) values (316, 'Soup - Campbells, Beef Barley', 1);
insert into orders (id, description, status) values (317, 'Lamb - Sausage Casings', 1);
insert into orders (id, description, status) values (318, 'Wine - Chateau Aqueria Tavel', 0);
insert into orders (id, description, status) values (319, 'Wine - Chablis J Moreau Et Fils', 0);
insert into orders (id, description, status) values (320, 'Ginger - Fresh', 2);
insert into orders (id, description, status) values (321, 'Cheese - Montery Jack', 2);
insert into orders (id, description, status) values (322, 'Cleaner - Bleach', 2);
insert into orders (id, description, status) values (323, 'Sugar - Invert', 1);
insert into orders (id, description, status) values (324, 'Lentils - Green, Dry', 2);
insert into orders (id, description, status) values (325, 'Zucchini - Green', 0);
insert into orders (id, description, status) values (326, 'Beans - Kidney White', 1);
insert into orders (id, description, status) values (327, 'Bacardi Raspberry', 2);
insert into orders (id, description, status) values (328, 'Appetizer - Sausage Rolls', 0);
insert into orders (id, description, status) values (329, 'Cup Translucent 9 Oz', 2);
insert into orders (id, description, status) values (330, 'Devonshire Cream', 1);
insert into orders (id, description, status) values (331, 'Pasta - Penne Primavera, Single', 0);
insert into orders (id, description, status) values (332, 'Container - Hngd Cll Blk 7x7x3', 0);
insert into orders (id, description, status) values (333, 'Ecolab - Hobart Upr Prewash Arm', 2);
insert into orders (id, description, status) values (334, 'Pastry - Apple Muffins - Mini', 1);
insert into orders (id, description, status) values (335, 'Water - Perrier', 1);
insert into orders (id, description, status) values (336, 'Pastrami', 1);
insert into orders (id, description, status) values (337, 'Monkfish - Fresh', 2);
insert into orders (id, description, status) values (338, 'Onions - Dried, Chopped', 2);
insert into orders (id, description, status) values (339, 'Nut - Peanut, Roasted', 0);
insert into orders (id, description, status) values (340, 'Carbonated Water - Blackcherry', 1);
insert into orders (id, description, status) values (341, 'Pepper - Orange', 1);
insert into orders (id, description, status) values (342, 'Wine - Cabernet Sauvignon', 1);
insert into orders (id, description, status) values (343, 'Croissants Thaw And Serve', 2);
insert into orders (id, description, status) values (344, 'Glycerine', 1);
insert into orders (id, description, status) values (345, 'Juice - V8, Tomato', 1);
insert into orders (id, description, status) values (346, 'Energy Drink - Franks Original', 1);
insert into orders (id, description, status) values (347, 'Appetiser - Bought', 1);
insert into orders (id, description, status) values (348, 'Calaloo', 0);
insert into orders (id, description, status) values (349, 'Juice - Ocean Spray Cranberry', 0);
insert into orders (id, description, status) values (350, 'Juice - Orange 1.89l', 2);
insert into orders (id, description, status) values (351, 'Wine - Zinfandel Rosenblum', 1);
insert into orders (id, description, status) values (352, 'Country Roll', 0);
insert into orders (id, description, status) values (353, 'Beef - Inside Round', 0);
insert into orders (id, description, status) values (354, 'Quail - Whole, Boneless', 0);
insert into orders (id, description, status) values (355, 'Smirnoff Green Apple Twist', 1);
insert into orders (id, description, status) values (356, 'Sauce - Soy Low Sodium - 3.87l', 1);
insert into orders (id, description, status) values (357, 'Potatoes - Mini White 3 Oz', 2);
insert into orders (id, description, status) values (358, 'Bread Base - Goodhearth', 2);
insert into orders (id, description, status) values (359, 'Sausage - Blood Pudding', 2);
insert into orders (id, description, status) values (360, 'Coconut Milk - Unsweetened', 1);
insert into orders (id, description, status) values (361, 'Placemat - Scallop, White', 1);
insert into orders (id, description, status) values (362, 'Cheese - Taleggio D.o.p.', 0);
insert into orders (id, description, status) values (363, 'Sausage - Liver', 0);
insert into orders (id, description, status) values (364, 'Soup - Campbells Beef Strogonoff', 0);
insert into orders (id, description, status) values (365, 'Tea - Earl Grey', 0);
insert into orders (id, description, status) values (366, 'Beef - Shank', 2);
insert into orders (id, description, status) values (367, 'Island Oasis - Sweet And Sour Mix', 2);
insert into orders (id, description, status) values (368, 'Peas - Pigeon, Dry', 0);
insert into orders (id, description, status) values (369, 'Skirt - 29 Foot', 1);
insert into orders (id, description, status) values (370, 'Juice - Happy Planet', 2);
insert into orders (id, description, status) values (371, 'Cup - Paper 10oz 92959', 1);
insert into orders (id, description, status) values (372, 'Chicken - Thigh, Bone In', 1);
insert into orders (id, description, status) values (373, 'Cheese - Montery Jack', 1);
insert into orders (id, description, status) values (374, 'Trueblue - Blueberry', 0);
insert into orders (id, description, status) values (375, 'Milk - 2% 250 Ml', 2);
insert into orders (id, description, status) values (376, 'Loaf Pan - 2 Lb, Foil', 1);
insert into orders (id, description, status) values (377, 'Soup - Clam Chowder, Dry Mix', 1);
insert into orders (id, description, status) values (378, 'Carbonated Water - Wildberry', 0);
insert into orders (id, description, status) values (379, 'Mushroom - Shitake, Dry', 0);
insert into orders (id, description, status) values (380, 'Ice Cream Bar - Oreo Sandwich', 1);
insert into orders (id, description, status) values (381, 'Bouq All Italian - Primerba', 1);
insert into orders (id, description, status) values (382, 'Tomato - Green', 2);
insert into orders (id, description, status) values (383, 'Longos - Cheese Tortellini', 1);
insert into orders (id, description, status) values (384, 'Coffee - Flavoured', 1);
insert into orders (id, description, status) values (385, 'Nut - Macadamia', 2);
insert into orders (id, description, status) values (386, 'Irish Cream - Baileys', 2);
insert into orders (id, description, status) values (387, 'Veal - Kidney', 0);
insert into orders (id, description, status) values (388, 'Longos - Penne With Pesto', 2);
insert into orders (id, description, status) values (389, 'Wine - Magnotta - Belpaese', 0);
insert into orders (id, description, status) values (390, 'Blue Curacao - Marie Brizard', 1);
insert into orders (id, description, status) values (391, 'Vinegar - Sherry', 2);
insert into orders (id, description, status) values (392, 'Juice - Cranberry, 341 Ml', 2);
insert into orders (id, description, status) values (393, 'Cherries - Fresh', 1);
insert into orders (id, description, status) values (394, 'Stock - Chicken, White', 1);
insert into orders (id, description, status) values (395, 'Wine - Tribal Sauvignon', 1);
insert into orders (id, description, status) values (396, 'Fish - Soup Base, Bouillon', 1);
insert into orders (id, description, status) values (397, 'Glass Clear 7 Oz Xl', 0);
insert into orders (id, description, status) values (398, 'Almonds Ground Blanched', 1);
insert into orders (id, description, status) values (399, 'Appetizer - Cheese Bites', 0);
insert into orders (id, description, status) values (400, 'Pineapple - Regular', 1);
insert into orders (id, description, status) values (401, 'Chocolate - Pistoles, White', 1);
insert into orders (id, description, status) values (402, 'Tea - Decaf Lipton', 0);
insert into orders (id, description, status) values (403, 'Beans - French', 1);
insert into orders (id, description, status) values (404, 'Bread Crumbs - Panko', 0);
insert into orders (id, description, status) values (405, 'Broom Handle', 2);
insert into orders (id, description, status) values (406, 'Scampi Tail', 0);
insert into orders (id, description, status) values (407, 'Peppercorns - Green', 2);
insert into orders (id, description, status) values (408, 'Wine - Semi Dry Riesling Vineland', 2);
insert into orders (id, description, status) values (409, 'Wine - Vineland Estate Semi - Dry', 2);
insert into orders (id, description, status) values (410, 'Slt - Individual Portions', 1);
insert into orders (id, description, status) values (411, 'Wine - Black Tower Qr', 0);
insert into orders (id, description, status) values (412, 'Melon - Watermelon, Seedless', 1);
insert into orders (id, description, status) values (413, 'Wine - Montecillo Rioja Crianza', 0);
insert into orders (id, description, status) values (414, 'Lamb - Racks, Frenched', 0);
insert into orders (id, description, status) values (415, 'Wine - Two Oceans Sauvignon', 0);
insert into orders (id, description, status) values (416, 'Bread - Hot Dog Buns', 0);
insert into orders (id, description, status) values (417, 'Sugar - Crumb', 0);
insert into orders (id, description, status) values (418, 'Wine - Tio Pepe Sherry Fino', 1);
insert into orders (id, description, status) values (419, 'Poppy Seed', 1);
insert into orders (id, description, status) values (420, 'Honey - Liquid', 0);
insert into orders (id, description, status) values (421, 'Coffee Decaf Colombian', 0);
insert into orders (id, description, status) values (422, 'Langers - Cranberry Cocktail', 0);
insert into orders (id, description, status) values (423, 'Cheese Cloth No 60', 1);
insert into orders (id, description, status) values (424, 'Nut - Chestnuts, Whole', 2);
insert into orders (id, description, status) values (425, 'Wine - Sicilia Igt Nero Avola', 1);
insert into orders (id, description, status) values (426, 'Pail With Metal Handle 16l White', 0);
insert into orders (id, description, status) values (427, 'Browning Caramel Glace', 1);
insert into orders (id, description, status) values (428, 'Wine - Chardonnay South', 0);
insert into orders (id, description, status) values (429, 'Wine - Clavet Saint Emilion', 2);
insert into orders (id, description, status) values (430, 'Rum - White, Gg White', 0);
insert into orders (id, description, status) values (431, 'Instant Coffee', 1);
insert into orders (id, description, status) values (432, 'Saskatoon Berries - Frozen', 0);
insert into orders (id, description, status) values (433, 'Chicken - Wieners', 0);
insert into orders (id, description, status) values (434, 'Napkin - Dinner, White', 1);
insert into orders (id, description, status) values (435, 'Nectarines', 0);
insert into orders (id, description, status) values (436, 'Filling - Mince Meat', 0);
insert into orders (id, description, status) values (437, 'The Pop Shoppe - Root Beer', 0);
insert into orders (id, description, status) values (438, 'Creme De Banane - Marie', 0);
insert into orders (id, description, status) values (439, 'Rosemary - Primerba, Paste', 2);
insert into orders (id, description, status) values (440, 'Bread - White Mini Epi', 0);
insert into orders (id, description, status) values (441, 'Bagelers', 2);
insert into orders (id, description, status) values (442, 'Red Currant Jelly', 1);
insert into orders (id, description, status) values (443, 'Bread - Raisin Walnut Pull', 0);
insert into orders (id, description, status) values (444, 'Russian Prince', 0);
insert into orders (id, description, status) values (445, 'Wine - Gato Negro Cabernet', 0);
insert into orders (id, description, status) values (446, 'Vinegar - White Wine', 1);
insert into orders (id, description, status) values (447, 'Soup - Knorr, Ministrone', 1);
insert into orders (id, description, status) values (448, 'Praline Paste', 0);
insert into orders (id, description, status) values (449, 'Wine - Gewurztraminer Pierre', 2);
insert into orders (id, description, status) values (450, 'Hold Up Tool Storage Rack', 0);
insert into orders (id, description, status) values (451, 'Parsley - Fresh', 1);
insert into orders (id, description, status) values (452, 'Seedlings - Mix, Organic', 1);
insert into orders (id, description, status) values (453, 'Lamb - Loin Chops', 1);
insert into orders (id, description, status) values (454, 'Cheese - Gouda', 1);
insert into orders (id, description, status) values (455, 'Flour Pastry Super Fine', 0);
insert into orders (id, description, status) values (456, 'Yucca', 0);
insert into orders (id, description, status) values (457, 'Lettuce - Radicchio', 1);
insert into orders (id, description, status) values (458, 'Muffin - Banana Nut Individual', 2);
insert into orders (id, description, status) values (459, 'Lid - 10,12,16 Oz', 2);
insert into orders (id, description, status) values (460, 'Shrimp - 21/25, Peel And Deviened', 2);
insert into orders (id, description, status) values (461, 'Wine - Beaujolais Villages', 1);
insert into orders (id, description, status) values (462, 'Shrimp - Black Tiger 6 - 8', 0);
insert into orders (id, description, status) values (463, 'Tuna - Bluefin', 2);
insert into orders (id, description, status) values (464, 'Trueblue - Blueberry 12x473ml', 2);
insert into orders (id, description, status) values (465, 'Pork - Sausage Casing', 1);
insert into orders (id, description, status) values (466, 'Daves Island Stinger', 2);
insert into orders (id, description, status) values (467, 'Ice Cream Bar - Rolo Cone', 1);
insert into orders (id, description, status) values (468, 'Lamb - Whole Head Off', 2);
insert into orders (id, description, status) values (469, 'Creme De Menthe Green', 1);
insert into orders (id, description, status) values (470, 'Bread Foccacia Whole', 1);
insert into orders (id, description, status) values (471, 'Coriander - Seed', 0);
insert into orders (id, description, status) values (472, 'Sachet', 1);
insert into orders (id, description, status) values (473, 'Wine - Prem Select Charddonany', 1);
insert into orders (id, description, status) values (474, 'Bols Melon Liqueur', 2);
insert into orders (id, description, status) values (475, 'Towels - Paper / Kraft', 0);
insert into orders (id, description, status) values (476, 'Bread - Multigrain', 2);
insert into orders (id, description, status) values (477, 'Mushroom - Oyster, Fresh', 2);
insert into orders (id, description, status) values (478, 'Beer - Rickards Red', 0);
insert into orders (id, description, status) values (479, 'Oil - Macadamia', 0);
insert into orders (id, description, status) values (480, 'Sherbet - Raspberry', 0);
insert into orders (id, description, status) values (481, 'Eggs - Extra Large', 1);
insert into orders (id, description, status) values (482, 'Initation Crab Meat', 2);
insert into orders (id, description, status) values (483, 'Flavouring - Rum', 0);
insert into orders (id, description, status) values (484, 'Beef - Baby, Liver', 2);
insert into orders (id, description, status) values (485, 'Pie Shell - 5', 2);
insert into orders (id, description, status) values (486, 'Crawfish', 2);
insert into orders (id, description, status) values (487, 'Wine - Cabernet Sauvignon', 1);
insert into orders (id, description, status) values (488, 'Bread - Mini Hamburger Bun', 2);
insert into orders (id, description, status) values (489, 'Wine - Beringer Founders Estate', 1);
insert into orders (id, description, status) values (490, 'Carbonated Water - Cherry', 1);
insert into orders (id, description, status) values (491, 'Wine - Ej Gallo Sierra Valley', 1);
insert into orders (id, description, status) values (492, 'Bread Base - Gold Formel', 0);
insert into orders (id, description, status) values (493, 'Beans - Fine', 0);
insert into orders (id, description, status) values (494, 'Star Fruit', 1);
insert into orders (id, description, status) values (495, 'Cheese Cloth No 100', 1);
insert into orders (id, description, status) values (496, 'Mushroom - Portebello', 0);
insert into orders (id, description, status) values (497, 'Bread Cranberry Foccacia', 2);
insert into orders (id, description, status) values (498, 'Ice Cream Bar - Oreo Cone', 1);
insert into orders (id, description, status) values (499, 'Lamb - Leg, Diced', 2);
insert into orders (id, description, status) values (500, 'Jerusalem Artichoke', 2);
insert into orders (id, description, status) values (501, 'Cheese - Fontina', 2);
insert into orders (id, description, status) values (502, 'Lettuce - Boston Bib - Organic', 2);
insert into orders (id, description, status) values (503, 'Grand Marnier', 1);
insert into orders (id, description, status) values (504, 'Crab - Soft Shell', 1);
insert into orders (id, description, status) values (505, 'Cookies - Englishbay Wht', 1);
insert into orders (id, description, status) values (506, 'Ice Cream - Strawberry', 1);
insert into orders (id, description, status) values (507, 'Mushrooms - Black, Dried', 2);
insert into orders (id, description, status) values (508, 'Sandwich Wrap', 0);
insert into orders (id, description, status) values (509, 'Wine - Niagara Peninsula Vqa', 1);
insert into orders (id, description, status) values (510, 'Wine - Sawmill Creek Autumn', 2);
insert into orders (id, description, status) values (511, 'Jerusalem Artichoke', 2);
insert into orders (id, description, status) values (512, 'Stock - Chicken, White', 0);
insert into orders (id, description, status) values (513, 'Table Cloth 62x120 White', 2);
insert into orders (id, description, status) values (514, 'Bread - Pullman, Sliced', 1);
insert into orders (id, description, status) values (515, 'Olives - Nicoise', 1);
insert into orders (id, description, status) values (516, 'Cookies Cereal Nut', 2);
insert into orders (id, description, status) values (517, 'Rum - Light, Captain Morgan', 2);
insert into orders (id, description, status) values (518, 'Glaze - Clear', 2);
insert into orders (id, description, status) values (519, 'Seedlings - Mix, Organic', 0);
insert into orders (id, description, status) values (520, 'Thermometer Digital', 0);
insert into orders (id, description, status) values (521, 'Soup Campbells Mexicali Tortilla', 0);
insert into orders (id, description, status) values (522, 'Pork - Shoulder', 1);
insert into orders (id, description, status) values (523, 'Zucchini - Yellow', 1);
insert into orders (id, description, status) values (524, 'Beef - Rib Roast, Cap On', 0);
insert into orders (id, description, status) values (525, 'Almonds Ground Blanched', 1);
insert into orders (id, description, status) values (526, 'Pepper - Paprika, Hungarian', 1);
insert into orders (id, description, status) values (527, 'Pepper - Red Bell', 0);
insert into orders (id, description, status) values (528, 'Island Oasis - Wildberry', 1);
insert into orders (id, description, status) values (529, 'Tea - English Breakfast', 1);
insert into orders (id, description, status) values (530, 'Nantucket - Kiwi Berry Cktl.', 1);
insert into orders (id, description, status) values (531, 'Cream - 10%', 2);
insert into orders (id, description, status) values (532, 'Steamers White', 0);
insert into orders (id, description, status) values (533, 'Pasta - Lasagne, Fresh', 0);
insert into orders (id, description, status) values (534, 'Bread - English Muffin', 2);
insert into orders (id, description, status) values (535, 'Maple Syrup', 2);
insert into orders (id, description, status) values (536, 'Pepper - Orange', 2);
insert into orders (id, description, status) values (537, 'Dill - Primerba, Paste', 1);
insert into orders (id, description, status) values (538, 'Bag - Clear 7 Lb', 1);
insert into orders (id, description, status) values (539, 'Venison - Denver Leg Boneless', 2);
insert into orders (id, description, status) values (540, 'Wine - White, Riesling, Henry Of', 1);
insert into orders (id, description, status) values (541, 'Bread - Raisin', 1);
insert into orders (id, description, status) values (542, 'Champagne - Brights, Dry', 1);
insert into orders (id, description, status) values (543, 'Ginsing - Fresh', 0);
insert into orders (id, description, status) values (544, 'Lobster - Cooked', 1);
insert into orders (id, description, status) values (545, 'Wine - Shiraz South Eastern', 0);
insert into orders (id, description, status) values (546, 'Croissant, Raw - Mini', 0);
insert into orders (id, description, status) values (547, 'Beer - Blue Light', 0);
insert into orders (id, description, status) values (548, 'Broom - Push', 1);
insert into orders (id, description, status) values (549, 'Dried Apple', 2);
insert into orders (id, description, status) values (550, 'Shrimp - 150 - 250', 0);
insert into orders (id, description, status) values (551, 'Lamb - Shanks', 2);
insert into orders (id, description, status) values (552, 'Muffin Batt - Choc Chk', 1);
insert into orders (id, description, status) values (553, 'Pumpkin - Seed', 2);
insert into orders (id, description, status) values (554, 'Beans - Butter Lrg Lima', 0);
insert into orders (id, description, status) values (555, 'Beans - Fava, Canned', 0);
insert into orders (id, description, status) values (556, 'Wine - Stoneliegh Sauvignon', 0);
insert into orders (id, description, status) values (557, 'Sugar - White Packet', 1);
insert into orders (id, description, status) values (558, 'Ecolab - Orange Frc, Cleaner', 2);
insert into orders (id, description, status) values (559, 'Cookies - Englishbay Wht', 0);
insert into orders (id, description, status) values (560, 'Gelatine Powder', 0);
insert into orders (id, description, status) values (561, 'Frangelico', 0);
insert into orders (id, description, status) values (562, 'Mushroom - Chanterelle Frozen', 1);
insert into orders (id, description, status) values (563, 'Cups 10oz Trans', 1);
insert into orders (id, description, status) values (564, 'Glass Clear 8 Oz', 1);
insert into orders (id, description, status) values (565, 'Pastry - Chocolate Marble Tea', 2);
insert into orders (id, description, status) values (566, 'Bar Mix - Lime', 1);
insert into orders (id, description, status) values (567, 'Veal - Leg', 2);
insert into orders (id, description, status) values (568, 'Sugar - Invert', 2);
insert into orders (id, description, status) values (569, 'Sparkling Wine - Rose, Freixenet', 1);
insert into orders (id, description, status) values (570, 'Cream - 10%', 1);
insert into orders (id, description, status) values (571, 'Wine - Alsace Gewurztraminer', 1);
insert into orders (id, description, status) values (572, 'Beans - Fava Fresh', 0);
insert into orders (id, description, status) values (573, 'Pepperoni Slices', 2);
insert into orders (id, description, status) values (574, 'Salt And Pepper Mix - Black', 1);
insert into orders (id, description, status) values (575, 'Turkey - Breast, Boneless Sk On', 1);
insert into orders (id, description, status) values (576, 'Bacardi Raspberry', 2);
insert into orders (id, description, status) values (577, 'Wine - Semi Dry Riesling Vineland', 0);
insert into orders (id, description, status) values (578, 'Trueblue - Blueberry Cranberry', 0);
insert into orders (id, description, status) values (579, 'Beef - Eye Of Round', 0);
insert into orders (id, description, status) values (580, 'Petit Baguette', 1);
insert into orders (id, description, status) values (581, 'Taro Leaves', 1);
insert into orders (id, description, status) values (582, 'Yams', 2);
insert into orders (id, description, status) values (583, 'Fish - Artic Char, Cold Smoked', 1);
insert into orders (id, description, status) values (584, 'Barramundi', 0);
insert into orders (id, description, status) values (585, 'Assorted Desserts', 1);
insert into orders (id, description, status) values (586, 'Pineapple - Regular', 2);
insert into orders (id, description, status) values (587, 'Arctic Char - Fillets', 2);
insert into orders (id, description, status) values (588, 'Nantucket Orange Juice', 0);
insert into orders (id, description, status) values (589, 'Dc Hikiage Hira Huba', 1);
insert into orders (id, description, status) values (590, 'Pork - Smoked Kassler', 1);
insert into orders (id, description, status) values (591, 'Sambuca - Opal Nera', 1);
insert into orders (id, description, status) values (592, 'Sprouts - Bean', 0);
insert into orders (id, description, status) values (593, 'Wine - Remy Pannier Rose', 1);
insert into orders (id, description, status) values (594, 'Hinge W Undercut', 0);
insert into orders (id, description, status) values (595, 'Beans - Turtle, Black, Dry', 1);
insert into orders (id, description, status) values (596, 'Cotton Wet Mop 16 Oz', 2);
insert into orders (id, description, status) values (597, 'Coriander - Seed', 0);
insert into orders (id, description, status) values (598, 'Wine - Tio Pepe Sherry Fino', 0);
insert into orders (id, description, status) values (599, 'Onions - Cooking', 2);
insert into orders (id, description, status) values (600, 'Cucumber - English', 2);
insert into orders (id, description, status) values (601, 'Energy Drink Bawls', 0);
insert into orders (id, description, status) values (602, 'Sour Puss Sour Apple', 2);
insert into orders (id, description, status) values (603, 'Veal - Inside Round / Top, Lean', 0);
insert into orders (id, description, status) values (604, 'Foam Dinner Plate', 1);
insert into orders (id, description, status) values (605, 'Soup - Knorr, Veg / Beef', 2);
insert into orders (id, description, status) values (606, 'Wine - Pinot Noir Stoneleigh', 0);
insert into orders (id, description, status) values (607, 'Cheese - Cambozola', 1);
insert into orders (id, description, status) values (608, 'Beef - Roasted, Cooked', 1);
insert into orders (id, description, status) values (609, 'Clementine', 2);
insert into orders (id, description, status) values (610, 'Fish - Scallops, Cold Smoked', 1);
insert into orders (id, description, status) values (611, 'Huck White Towels', 2);
insert into orders (id, description, status) values (612, 'Wine - White Cab Sauv.on', 2);
insert into orders (id, description, status) values (613, 'Puff Pastry - Sheets', 1);
insert into orders (id, description, status) values (614, 'Beer - Blue', 2);
insert into orders (id, description, status) values (615, 'Sorrel - Fresh', 0);
insert into orders (id, description, status) values (616, 'Carbonated Water - Blackberry', 2);
insert into orders (id, description, status) values (617, 'Sauce - Soya, Light', 0);
insert into orders (id, description, status) values (618, 'Cheese - Augre Des Champs', 0);
insert into orders (id, description, status) values (619, 'Lettuce - Lolla Rosa', 1);
insert into orders (id, description, status) values (620, 'Anchovy Paste - 56 G Tube', 1);
insert into orders (id, description, status) values (621, 'Beef - Prime Rib Aaa', 2);
insert into orders (id, description, status) values (622, 'Beer - Molson Excel', 0);
insert into orders (id, description, status) values (623, 'Guinea Fowl', 1);
insert into orders (id, description, status) values (624, 'Beans - Navy, Dry', 0);
insert into orders (id, description, status) values (625, 'Cookie Trail Mix', 2);
insert into orders (id, description, status) values (626, 'Chips Potato All Dressed - 43g', 0);
insert into orders (id, description, status) values (627, 'Sobe - Tropical Energy', 0);
insert into orders (id, description, status) values (628, 'Bread - Wheat Baguette', 1);
insert into orders (id, description, status) values (629, 'Table Cloth 120 Round White', 1);
insert into orders (id, description, status) values (630, 'Shark - Loin', 1);
insert into orders (id, description, status) values (631, 'Shrimp - Black Tiger 26/30', 2);
insert into orders (id, description, status) values (632, 'Sultanas', 1);
insert into orders (id, description, status) values (633, 'Bag - Regular Kraft 20 Lb', 0);
insert into orders (id, description, status) values (634, 'Liners - Banana, Paper', 1);
insert into orders (id, description, status) values (635, 'Chicken - Whole Roasting', 1);
insert into orders (id, description, status) values (636, 'Burger Veggie', 0);
insert into orders (id, description, status) values (637, 'Juice - Prune', 1);
insert into orders (id, description, status) values (638, 'Carbonated Water - Orange', 0);
insert into orders (id, description, status) values (639, 'Fib N9 - Prague Powder', 2);
insert into orders (id, description, status) values (640, 'Lettuce - Sea / Sea Asparagus', 2);
insert into orders (id, description, status) values (641, 'Squid - U 5', 1);
insert into orders (id, description, status) values (642, 'Oil - Shortening - All - Purpose', 2);
insert into orders (id, description, status) values (643, 'Coconut - Whole', 2);
insert into orders (id, description, status) values (644, 'Pork - Kidney', 2);
insert into orders (id, description, status) values (645, 'Raspberries - Fresh', 0);
insert into orders (id, description, status) values (646, 'Cheese - Colby', 2);
insert into orders (id, description, status) values (647, 'Wine - Duboeuf Beaujolais', 0);
insert into orders (id, description, status) values (648, 'Tart Shells - Savory, 3', 0);
insert into orders (id, description, status) values (649, 'Arizona - Plum Green Tea', 0);
insert into orders (id, description, status) values (650, 'Wine - Sauvignon Blanc', 0);
insert into orders (id, description, status) values (651, 'Wine - Red, Cabernet Merlot', 0);
insert into orders (id, description, status) values (652, 'Lobster - Baby, Boiled', 1);
insert into orders (id, description, status) values (653, 'Wine - Black Tower Qr', 0);
insert into orders (id, description, status) values (654, 'Wine - Vovray Sec Domaine Huet', 2);
insert into orders (id, description, status) values (655, 'Pike - Frozen Fillet', 0);
insert into orders (id, description, status) values (656, 'Muffin Batt - Ban Dream Zero', 0);
insert into orders (id, description, status) values (657, 'Stock - Beef, White', 0);
insert into orders (id, description, status) values (658, 'Wine - White, Pelee Island', 1);
insert into orders (id, description, status) values (659, 'Olives - Green, Pitted', 1);
insert into orders (id, description, status) values (660, 'Poppy Seed', 1);
insert into orders (id, description, status) values (661, 'Wine La Vielle Ferme Cote Du', 2);
insert into orders (id, description, status) values (662, 'Lamb - Whole Head Off', 2);
insert into orders (id, description, status) values (663, 'Soup - Campbells Bean Medley', 2);
insert into orders (id, description, status) values (664, 'Wine - Marlbourough Sauv Blanc', 2);
insert into orders (id, description, status) values (665, 'Worcestershire Sauce', 0);
insert into orders (id, description, status) values (666, 'Pork - Shoulder', 0);
insert into orders (id, description, status) values (667, 'Sobe - Berry Energy', 0);
insert into orders (id, description, status) values (668, 'Beef Cheek Fresh', 2);
insert into orders (id, description, status) values (669, 'Bread - Multigrain, Loaf', 1);
insert into orders (id, description, status) values (670, 'Wine - Wyndham Estate Bin 777', 1);
insert into orders (id, description, status) values (671, 'Tea - Vanilla Chai', 2);
insert into orders (id, description, status) values (672, 'Cheese - Marble', 0);
insert into orders (id, description, status) values (673, 'Coffee Cup 16oz Foam', 0);
insert into orders (id, description, status) values (674, 'Bread - Pullman, Sliced', 2);
insert into orders (id, description, status) values (675, 'Juice - Grapefruit, 341 Ml', 2);
insert into orders (id, description, status) values (676, 'Oneshot Automatic Soap System', 0);
insert into orders (id, description, status) values (677, 'Fish - Artic Char, Cold Smoked', 2);
insert into orders (id, description, status) values (678, 'Nori Sea Weed - Gold Label', 1);
insert into orders (id, description, status) values (679, 'Beef - Ox Tongue', 1);
insert into orders (id, description, status) values (680, 'Chicken - Base, Ultimate', 2);
insert into orders (id, description, status) values (681, 'Bar Nature Valley', 1);
insert into orders (id, description, status) values (682, 'Honey - Comb', 2);
insert into orders (id, description, status) values (683, 'Eel Fresh', 2);
insert into orders (id, description, status) values (684, 'Sproutsmustard Cress', 1);
insert into orders (id, description, status) values (685, 'Salt - Kosher', 0);
insert into orders (id, description, status) values (686, 'Flavouring - Raspberry', 0);
insert into orders (id, description, status) values (687, 'Mint - Fresh', 1);
insert into orders (id, description, status) values (688, 'Lid - Translucent, 3.5 And 6 Oz', 2);
insert into orders (id, description, status) values (689, 'Pastrami', 1);
insert into orders (id, description, status) values (690, 'Wine - Semi Dry Riesling Vineland', 2);
insert into orders (id, description, status) values (691, 'Fuji Apples', 2);
insert into orders (id, description, status) values (692, 'Muffin Mix - Chocolate Chip', 1);
insert into orders (id, description, status) values (693, 'Veal - Sweetbread', 2);
insert into orders (id, description, status) values (694, 'Smoked Paprika', 1);
insert into orders (id, description, status) values (695, 'Kale - Red', 1);
insert into orders (id, description, status) values (696, 'Muffin Chocolate Individual Wrap', 0);
insert into orders (id, description, status) values (697, 'Water Chestnut - Canned', 0);
insert into orders (id, description, status) values (698, 'Flour - Chickpea', 2);
insert into orders (id, description, status) values (699, 'Pimento - Canned', 1);
insert into orders (id, description, status) values (700, 'Apron', 1);
insert into orders (id, description, status) values (701, 'Creme De Menthe Green', 2);
insert into orders (id, description, status) values (702, 'Vaccum Bag - 14x20', 2);
insert into orders (id, description, status) values (703, 'Olive - Spread Tapenade', 2);
insert into orders (id, description, status) values (704, 'Wine - Lou Black Shiraz', 0);
insert into orders (id, description, status) values (705, 'Lemonade - Black Cherry, 591 Ml', 1);
insert into orders (id, description, status) values (706, 'Mustard - Pommery', 0);
insert into orders (id, description, status) values (707, 'Lettuce - Escarole', 1);
insert into orders (id, description, status) values (708, 'Oven Mitt - 13 Inch', 0);
insert into orders (id, description, status) values (709, 'Steamers White', 1);
insert into orders (id, description, status) values (710, 'Lamb Shoulder Boneless Nz', 1);
insert into orders (id, description, status) values (711, 'Beef - Flank Steak', 1);
insert into orders (id, description, status) values (712, 'Schnappes - Peach, Walkers', 2);
insert into orders (id, description, status) values (713, 'Artichokes - Knobless, White', 1);
insert into orders (id, description, status) values (714, 'Veal - Brisket, Provimi, Bone - In', 1);
insert into orders (id, description, status) values (715, 'Sobe - Berry Energy', 0);
insert into orders (id, description, status) values (716, 'Muffin Hinge 117n', 2);
insert into orders (id, description, status) values (717, 'Breakfast Quesadillas', 0);
insert into orders (id, description, status) values (718, 'Compound - Pear', 2);
insert into orders (id, description, status) values (719, 'Flour - Bread', 2);
insert into orders (id, description, status) values (720, 'Sherry - Dry', 2);
insert into orders (id, description, status) values (721, 'Hog / Sausage Casing - Pork', 0);
insert into orders (id, description, status) values (722, 'Wine - Red, Cabernet Sauvignon', 2);
insert into orders (id, description, status) values (723, 'Chips Potato Salt Vinegar 43g', 1);
insert into orders (id, description, status) values (724, 'Bread - Frozen Basket Variety', 2);
insert into orders (id, description, status) values (725, 'Juice - Apple, 1.36l', 0);
insert into orders (id, description, status) values (726, 'Salt - Table', 0);
insert into orders (id, description, status) values (727, 'Chocolate - Semi Sweet, Calets', 0);
insert into orders (id, description, status) values (728, 'Grapefruit - Pink', 2);
insert into orders (id, description, status) values (729, 'Chicken Giblets', 2);
insert into orders (id, description, status) values (730, 'Pears - Anjou', 1);
insert into orders (id, description, status) values (731, 'Dc Hikiage Hira Huba', 1);
insert into orders (id, description, status) values (732, 'Extract - Vanilla,artificial', 1);
insert into orders (id, description, status) values (733, 'Flour - Strong Pizza', 1);
insert into orders (id, description, status) values (734, 'Raisin - Dark', 2);
insert into orders (id, description, status) values (735, 'Wine - Cava Aria Estate Brut', 2);
insert into orders (id, description, status) values (736, 'Beans - Soya Bean', 0);
insert into orders (id, description, status) values (737, 'Chocolate - Semi Sweet', 2);
insert into orders (id, description, status) values (738, 'Hot Choc Vending', 2);
insert into orders (id, description, status) values (739, 'Olive - Spread Tapenade', 0);
insert into orders (id, description, status) values (740, 'Bagel - Everything Presliced', 1);
insert into orders (id, description, status) values (741, 'Appetizer - Mango Chevre', 1);
insert into orders (id, description, status) values (742, 'Danishes - Mini Raspberry', 2);
insert into orders (id, description, status) values (743, 'Appetizer - Tarragon Chicken', 0);
insert into orders (id, description, status) values (744, 'Soho Lychee Liqueur', 0);
insert into orders (id, description, status) values (745, 'Wine - Magnotta - Belpaese', 0);
insert into orders (id, description, status) values (746, 'Scallops - 20/30', 0);
insert into orders (id, description, status) values (747, 'Bagel - Everything', 1);
insert into orders (id, description, status) values (748, 'Table Cloth 53x53 White', 1);
insert into orders (id, description, status) values (749, 'Bread - White, Sliced', 0);
insert into orders (id, description, status) values (750, 'Wine - Port Late Bottled Vintage', 2);
insert into orders (id, description, status) values (751, 'Liquid Aminios Acid - Braggs', 0);
insert into orders (id, description, status) values (752, 'Pepperoni Slices', 1);
insert into orders (id, description, status) values (753, 'Rice - Sushi', 1);
insert into orders (id, description, status) values (754, 'Veal - Inside, Choice', 0);
insert into orders (id, description, status) values (755, 'Bread - Bistro Sour', 0);
insert into orders (id, description, status) values (756, 'Mayonnaise - Individual Pkg', 1);
insert into orders (id, description, status) values (757, 'Bread - Multigrain Oval', 2);
insert into orders (id, description, status) values (758, 'Schnappes - Peach, Walkers', 1);
insert into orders (id, description, status) values (759, 'Pasta - Ravioli', 2);
insert into orders (id, description, status) values (760, 'Iced Tea Concentrate', 0);
insert into orders (id, description, status) values (761, 'Mace', 0);
insert into orders (id, description, status) values (762, 'Spice - Onion Powder Granulated', 2);
insert into orders (id, description, status) values (763, 'Soup Campbells - Tomato Bisque', 2);
insert into orders (id, description, status) values (764, 'Soup - Campbells Beef Strogonoff', 0);
insert into orders (id, description, status) values (765, 'Baking Powder', 0);
insert into orders (id, description, status) values (766, 'Wine - Redchard Merritt', 2);
insert into orders (id, description, status) values (767, 'Mushroom - Lg - Cello', 0);
insert into orders (id, description, status) values (768, 'Cheese - Cheddar With Claret', 2);
insert into orders (id, description, status) values (769, 'Pasta - Cannelloni, Sheets, Fresh', 0);
insert into orders (id, description, status) values (770, 'Calypso - Black Cherry Lemonade', 0);
insert into orders (id, description, status) values (771, 'Vacuum Bags 12x16', 1);
insert into orders (id, description, status) values (772, 'Cabbage - Green', 1);
insert into orders (id, description, status) values (773, 'Beef Dry Aged Tenderloin Aaa', 0);
insert into orders (id, description, status) values (774, 'Asparagus - Frozen', 1);
insert into orders (id, description, status) values (775, 'Soup - Campbells, Butternut', 2);
insert into orders (id, description, status) values (776, 'Veal - Brisket, Provimi, Bone - In', 0);
insert into orders (id, description, status) values (777, 'Wine - Prem Select Charddonany', 0);
insert into orders (id, description, status) values (778, 'Truffle Paste', 2);
insert into orders (id, description, status) values (779, 'Veal - Ground', 2);
insert into orders (id, description, status) values (780, 'Carbonated Water - White Grape', 2);
insert into orders (id, description, status) values (781, 'Cookie Dough - Peanut Butter', 2);
insert into orders (id, description, status) values (782, 'Flounder - Fresh', 1);
insert into orders (id, description, status) values (783, 'Seedlings - Mix, Organic', 2);
insert into orders (id, description, status) values (784, 'Pork - Loin, Boneless', 1);
insert into orders (id, description, status) values (785, 'Nacho Chips', 2);
insert into orders (id, description, status) values (786, 'Wine - Vouvray Cuvee Domaine', 2);
insert into orders (id, description, status) values (787, 'Sauce - Salsa', 2);
insert into orders (id, description, status) values (788, 'Beans - Soya Bean', 0);
insert into orders (id, description, status) values (789, 'Lobster - Tail, 3 - 4 Oz', 2);
insert into orders (id, description, status) values (790, 'Cream - 35%', 2);
insert into orders (id, description, status) values (791, 'Broom - Push', 1);
insert into orders (id, description, status) values (792, 'Beef - Sushi Flat Iron Steak', 1);
insert into orders (id, description, status) values (793, 'Pie Filling - Pumpkin', 1);
insert into orders (id, description, status) values (794, 'Blackberries', 2);
insert into orders (id, description, status) values (795, 'Vector Energy Bar', 1);
insert into orders (id, description, status) values (796, 'Mousse - Mango', 1);
insert into orders (id, description, status) values (797, 'Bread - Roll, Whole Wheat', 2);
insert into orders (id, description, status) values (798, 'Bandage - Fexible 1x3', 0);
insert into orders (id, description, status) values (799, 'Schnappes - Peach, Walkers', 2);
insert into orders (id, description, status) values (800, 'Spoon - Soup, Plastic', 1);
insert into orders (id, description, status) values (801, 'Lettuce - Lolla Rosa', 2);
insert into orders (id, description, status) values (802, 'Pectin', 0);
insert into orders (id, description, status) values (803, 'Veal - Inside Round / Top, Lean', 1);
insert into orders (id, description, status) values (804, 'Bagel - Everything Presliced', 2);
insert into orders (id, description, status) values (805, 'Long Island Ice Tea', 0);
insert into orders (id, description, status) values (806, 'Soup - Campbells Beef Noodle', 2);
insert into orders (id, description, status) values (807, 'Vinegar - Balsamic', 0);
insert into orders (id, description, status) values (808, 'Mushroom - Enoki, Fresh', 0);
insert into orders (id, description, status) values (809, 'Mushroom - Morel Frozen', 0);
insert into orders (id, description, status) values (810, 'Cheese - Cheddarsliced', 2);
insert into orders (id, description, status) values (811, 'Wine - Red, Lurton Merlot De', 2);
insert into orders (id, description, status) values (812, 'Graham Cracker Mix', 2);
insert into orders (id, description, status) values (813, 'Pie Shell - 5', 1);
insert into orders (id, description, status) values (814, 'Wasabi Powder', 1);
insert into orders (id, description, status) values (815, 'Silicone Parch. 16.3x24.3', 1);
insert into orders (id, description, status) values (816, 'Club Soda - Schweppes, 355 Ml', 1);
insert into orders (id, description, status) values (817, 'Icecream - Dstk Cml And Fdg', 0);
insert into orders (id, description, status) values (818, 'Cheese - Asiago', 1);
insert into orders (id, description, status) values (819, 'Salt - Kosher', 2);
insert into orders (id, description, status) values (820, 'Crackers - Melba Toast', 1);
insert into orders (id, description, status) values (821, 'Tart - Pecan Butter Squares', 0);
insert into orders (id, description, status) values (822, 'Tart - Raisin And Pecan', 2);
insert into orders (id, description, status) values (823, 'Cheese - Cream Cheese', 0);
insert into orders (id, description, status) values (824, 'Sorrel - Fresh', 1);
insert into orders (id, description, status) values (825, 'Onions - Cippolini', 0);
insert into orders (id, description, status) values (826, 'Wine - Savigny - Les - Beaune', 0);
insert into orders (id, description, status) values (827, 'Veal Inside - Provimi', 2);
insert into orders (id, description, status) values (828, 'Cup - 3.5oz, Foam', 0);
insert into orders (id, description, status) values (829, 'Appetizer - Smoked Salmon / Dill', 2);
insert into orders (id, description, status) values (830, 'Wine - Chateau Aqueria Tavel', 1);
insert into orders (id, description, status) values (831, 'Ginger - Ground', 0);
insert into orders (id, description, status) values (832, 'Tea - Decaf Lipton', 2);
insert into orders (id, description, status) values (833, 'Pike - Frozen Fillet', 1);
insert into orders (id, description, status) values (834, 'Nut - Cashews, Whole, Raw', 0);
insert into orders (id, description, status) values (835, 'Beef - Ox Tail, Frozen', 2);
insert into orders (id, description, status) values (836, 'Wine - Redchard Merritt', 1);
insert into orders (id, description, status) values (837, 'Wine - Chablis 2003 Champs', 0);
insert into orders (id, description, status) values (838, 'Muffin Mix - Blueberry', 0);
insert into orders (id, description, status) values (839, 'Cheese - Brie Roitelet', 0);
insert into orders (id, description, status) values (840, 'Crackers - Water', 1);
insert into orders (id, description, status) values (841, 'Appetizer - Mini Egg Roll, Shrimp', 2);
insert into orders (id, description, status) values (842, 'Wine - White, French Cross', 2);
insert into orders (id, description, status) values (843, 'Ham - Black Forest', 0);
insert into orders (id, description, status) values (844, 'Apple - Custard', 2);
insert into orders (id, description, status) values (845, 'Cream - 18%', 0);
insert into orders (id, description, status) values (846, 'Sauce - Soya, Light', 0);
insert into orders (id, description, status) values (847, 'Avocado', 0);
insert into orders (id, description, status) values (848, 'Pineapple - Canned, Rings', 2);
insert into orders (id, description, status) values (849, 'Wine - Remy Pannier Rose', 0);
insert into orders (id, description, status) values (850, 'Skirt - 24 Foot', 0);
insert into orders (id, description, status) values (851, 'Flour - Bread', 2);
insert into orders (id, description, status) values (852, 'Chocolate - Dark', 2);
insert into orders (id, description, status) values (853, 'Pastry - Banana Tea Loaf', 0);
insert into orders (id, description, status) values (854, 'Extract - Rum', 2);
insert into orders (id, description, status) values (855, 'Cucumber - Pickling Ontario', 1);
insert into orders (id, description, status) values (856, 'Bread - Malt', 2);
insert into orders (id, description, status) values (857, 'Jam - Raspberry', 0);
insert into orders (id, description, status) values (858, 'Carrots - Mini Red Organic', 0);
insert into orders (id, description, status) values (859, 'Extract - Raspberry', 1);
insert into orders (id, description, status) values (860, 'Pineapple - Canned, Rings', 0);
insert into orders (id, description, status) values (861, 'Pepsi, 355 Ml', 1);
insert into orders (id, description, status) values (862, 'Clams - Littleneck, Whole', 2);
insert into orders (id, description, status) values (863, 'Bar Energy Chocchip', 0);
insert into orders (id, description, status) values (864, 'Cookies - Oreo, 4 Pack', 2);
insert into orders (id, description, status) values (865, 'Rosemary - Fresh', 1);
insert into orders (id, description, status) values (866, 'Taro Root', 2);
insert into orders (id, description, status) values (867, 'Toothpick Frilled', 1);
insert into orders (id, description, status) values (868, 'Gatorade - Fruit Punch', 0);
insert into orders (id, description, status) values (869, 'Dragon Fruit', 0);
insert into orders (id, description, status) values (870, 'Pickles - Gherkins', 0);
insert into orders (id, description, status) values (871, 'Bouillion - Fish', 2);
insert into orders (id, description, status) values (872, 'Kellogs All Bran Bars', 1);
insert into orders (id, description, status) values (873, 'Sauce - Marinara', 1);
insert into orders (id, description, status) values (874, 'Wine - Jaboulet Cotes Du Rhone', 0);
insert into orders (id, description, status) values (875, 'Momiji Oroshi Chili Sauce', 2);
insert into orders (id, description, status) values (876, 'Wine - Saint Emilion Calvet', 1);
insert into orders (id, description, status) values (877, 'Beans - Butter Lrg Lima', 1);
insert into orders (id, description, status) values (878, 'Barley - Pearl', 1);
insert into orders (id, description, status) values (879, 'Juice - Grape, White', 0);
insert into orders (id, description, status) values (880, 'Soup - Campbells Bean Medley', 0);
insert into orders (id, description, status) values (881, 'Tea - Herbal I Love Lemon', 2);
insert into orders (id, description, status) values (882, 'Pickles - Gherkins', 2);
insert into orders (id, description, status) values (883, 'Wine - Cotes Du Rhone', 1);
insert into orders (id, description, status) values (884, 'Cake - Mini Potato Pancake', 2);
insert into orders (id, description, status) values (885, 'Cookies Oatmeal Raisin', 0);
insert into orders (id, description, status) values (886, 'Salsify, Organic', 1);
insert into orders (id, description, status) values (887, 'Salt - Rock, Course', 0);
insert into orders (id, description, status) values (888, 'Soup - Knorr, Veg / Beef', 0);
insert into orders (id, description, status) values (889, 'Creamers - 10%', 2);
insert into orders (id, description, status) values (890, 'Dry Ice', 0);
insert into orders (id, description, status) values (891, 'Dill Weed - Dry', 2);
insert into orders (id, description, status) values (892, 'Seaweed Green Sheets', 2);
insert into orders (id, description, status) values (893, 'Tart Shells - Sweet, 4', 1);
insert into orders (id, description, status) values (894, 'Rice - Sushi', 0);
insert into orders (id, description, status) values (895, 'Scallops 60/80 Iqf', 0);
insert into orders (id, description, status) values (896, 'Beer - Molson Excel', 1);
insert into orders (id, description, status) values (897, 'Wine - Saint Emilion Calvet', 2);
insert into orders (id, description, status) values (898, 'Sage Derby', 2);
insert into orders (id, description, status) values (899, 'Wine - White, Concha Y Toro', 0);
insert into orders (id, description, status) values (900, 'Coffee - Dark Roast', 0);
insert into orders (id, description, status) values (901, 'Wine - Riesling Dr. Pauly', 0);
insert into orders (id, description, status) values (902, 'Mudslide', 2);
insert into orders (id, description, status) values (903, 'Lemonade - Kiwi, 591 Ml', 0);
insert into orders (id, description, status) values (904, 'Tomatoes - Cherry', 1);
insert into orders (id, description, status) values (905, 'Coffee Cup 16oz Foam', 1);
insert into orders (id, description, status) values (906, 'Pastry - Chocolate Marble Tea', 2);
insert into orders (id, description, status) values (907, 'Soup - Campbells, Cream Of', 1);
insert into orders (id, description, status) values (908, 'Lettuce - Curly Endive', 1);
insert into orders (id, description, status) values (909, 'Wiberg Cure', 2);
insert into orders (id, description, status) values (910, 'Wine - White Cab Sauv.on', 1);
insert into orders (id, description, status) values (911, 'Wine - Magnotta - Bel Paese White', 0);
insert into orders (id, description, status) values (912, 'Swiss Chard', 1);
insert into orders (id, description, status) values (913, 'Chicken - Soup Base', 2);
insert into orders (id, description, status) values (914, 'Plate Pie Foil', 2);
insert into orders (id, description, status) values (915, 'Wine - Mondavi Coastal Private', 1);
insert into orders (id, description, status) values (916, 'Potatoes - Yukon Gold, 80 Ct', 2);
insert into orders (id, description, status) values (917, 'Guava', 0);
insert into orders (id, description, status) values (918, 'Oil - Truffle, Black', 2);
insert into orders (id, description, status) values (919, 'Scampi Tail', 2);
insert into orders (id, description, status) values (920, 'Wine - White, Pelee Island', 2);
insert into orders (id, description, status) values (921, 'Sobe - Green Tea', 1);
insert into orders (id, description, status) values (922, 'Onions - White', 1);
insert into orders (id, description, status) values (923, 'Cabbage - Nappa', 1);
insert into orders (id, description, status) values (924, 'Butter Balls Salted', 0);
insert into orders (id, description, status) values (925, 'Wine - White, Schroder And Schyl', 1);
insert into orders (id, description, status) values (926, 'Yogurt - Strawberry, 175 Gr', 0);
insert into orders (id, description, status) values (927, 'Soup - Knorr, Veg / Beef', 1);
insert into orders (id, description, status) values (928, 'Pastry - French Mini Assorted', 0);
insert into orders (id, description, status) values (929, 'Olives - Stuffed', 1);
insert into orders (id, description, status) values (930, 'Chilli Paste, Hot Sambal Oelek', 0);
insert into orders (id, description, status) values (931, 'Apple - Delicious, Red', 2);
insert into orders (id, description, status) values (932, 'Mustard - Seed', 2);
insert into orders (id, description, status) values (933, 'Cleaner - Comet', 2);
insert into orders (id, description, status) values (934, 'Onions Granulated', 2);
insert into orders (id, description, status) values (935, 'Mushroom - Shitake, Dry', 1);
insert into orders (id, description, status) values (936, 'Sauce - Black Current, Dry Mix', 1);
insert into orders (id, description, status) values (937, 'Lumpfish Black', 0);
insert into orders (id, description, status) values (938, 'Truffle Shells - White Chocolate', 2);
insert into orders (id, description, status) values (939, 'Soup - Campbells Bean Medley', 1);
insert into orders (id, description, status) values (940, 'Mousse - Passion Fruit', 2);
insert into orders (id, description, status) values (941, 'Oil - Pumpkinseed', 0);
insert into orders (id, description, status) values (942, 'Soup - Campbells, Minestrone', 1);
insert into orders (id, description, status) values (943, 'Cheese - Colby', 2);
insert into orders (id, description, status) values (944, 'Nut - Hazelnut, Whole', 0);
insert into orders (id, description, status) values (945, 'Fruit Salad Deluxe', 2);
insert into orders (id, description, status) values (946, 'Soup - Campbells, Chix Gumbo', 1);
insert into orders (id, description, status) values (947, 'Soup - Clam Chowder, Dry Mix', 0);
insert into orders (id, description, status) values (948, 'Appetizer - Tarragon Chicken', 1);
insert into orders (id, description, status) values (949, 'Wine - Sicilia Igt Nero Avola', 2);
insert into orders (id, description, status) values (950, 'Beef - Tenderlion, Center Cut', 0);
insert into orders (id, description, status) values (951, 'Lettuce - Curly Endive', 2);
insert into orders (id, description, status) values (952, 'Cocoa Powder - Dutched', 0);
insert into orders (id, description, status) values (953, 'Wine - Niagara Peninsula Vqa', 1);
insert into orders (id, description, status) values (954, 'Crush - Grape, 355 Ml', 0);
insert into orders (id, description, status) values (955, 'Venison - Ground', 0);
insert into orders (id, description, status) values (956, 'Bouq All Italian - Primerba', 0);
insert into orders (id, description, status) values (957, 'Gloves - Goldtouch Disposable', 0);
insert into orders (id, description, status) values (958, 'Tomatoes - Heirloom', 1);
insert into orders (id, description, status) values (959, 'Crab - Dungeness, Whole', 1);
insert into orders (id, description, status) values (960, 'Blueberries', 0);
insert into orders (id, description, status) values (961, 'Mortadella', 2);
insert into orders (id, description, status) values (962, 'Mushroom - Morel Frozen', 0);
insert into orders (id, description, status) values (963, 'Fuji Apples', 2);
insert into orders (id, description, status) values (964, 'Oneshot Automatic Soap System', 0);
insert into orders (id, description, status) values (965, 'Pork - Side Ribs', 2);
insert into orders (id, description, status) values (966, 'Beef - Bresaola', 0);
insert into orders (id, description, status) values (967, 'Shrimp - Prawn', 0);
insert into orders (id, description, status) values (968, 'Port - 74 Brights', 2);
insert into orders (id, description, status) values (969, 'Chocolate - Compound Coating', 0);
insert into orders (id, description, status) values (970, 'Ecolab - Hand Soap Form Antibac', 1);
insert into orders (id, description, status) values (971, 'Chocolate Eclairs', 2);
insert into orders (id, description, status) values (972, 'Bread Base - Gold Formel', 0);
insert into orders (id, description, status) values (973, 'Cup Translucent 9 Oz', 1);
insert into orders (id, description, status) values (974, 'Juice - Orangina', 2);
insert into orders (id, description, status) values (975, 'Pork - Belly Fresh', 1);
insert into orders (id, description, status) values (976, 'Kirsch - Schloss', 0);
insert into orders (id, description, status) values (977, 'Lemons', 2);
insert into orders (id, description, status) values (978, 'Lime Cordial - Roses', 1);
insert into orders (id, description, status) values (979, 'Bread Base - Goodhearth', 2);
insert into orders (id, description, status) values (980, 'Pasta - Fettuccine, Egg, Fresh', 1);
insert into orders (id, description, status) values (981, 'Tarragon - Fresh', 0);
insert into orders (id, description, status) values (982, 'Contreau', 2);
insert into orders (id, description, status) values (983, 'Haggis', 1);
insert into orders (id, description, status) values (984, 'Placemat - Scallop, White', 2);
insert into orders (id, description, status) values (985, 'Beef - Flank Steak', 2);
insert into orders (id, description, status) values (986, 'Sprouts - Alfalfa', 0);
insert into orders (id, description, status) values (987, 'Capers - Ox Eye Daisy', 2);
insert into orders (id, description, status) values (988, 'Noodles - Steamed Chow Mein', 1);
insert into orders (id, description, status) values (989, 'Tea - Vanilla Chai', 1);
insert into orders (id, description, status) values (990, 'Chicken - Leg, Boneless', 1);
insert into orders (id, description, status) values (991, 'Soup - Knorr, Ministrone', 1);
insert into orders (id, description, status) values (992, 'Nut - Almond, Blanched, Whole', 0);
insert into orders (id, description, status) values (993, 'Raspberries - Frozen', 2);
insert into orders (id, description, status) values (994, 'Corn Shoots', 1);
insert into orders (id, description, status) values (995, 'Beef - Top Sirloin - Aaa', 1);
insert into orders (id, description, status) values (996, 'Corn - Mini', 0);
insert into orders (id, description, status) values (997, 'Sachet', 2);
insert into orders (id, description, status) values (998, 'Pepper - White, Ground', 2);
insert into orders (id, description, status) values (999, 'Beef - Rib Roast, Cap On', 1);
insert into orders (id, description, status) values (1000, 'Juice - V8, Tomato', 2);
